<doc size="A4">
    <style>
        page:
            margin: 0
            padding: 0
            border: 0
        row:
            margin: 0
            padding: 0
            border: 0
        cell:
            margin: 0
            padding: 0
            border: 0
        class:
            value:
                align: right
            total_label:
                align: right
            heading:
                align: center
                font-face: Helvetica-Bold
                font-size: 10
            overdue:
                font-color: red
                border-color: red
            total-amount:
                font-face: Helvetica-Bold
                align: right
            busname:
                font-face: Courier10Pitch
                font-size: 32
                font-lead: 36
                align: right
            title:
                font-size: 24
                font-lead: 26
                align: right
    </style>
    <page>
        <header margin="5" padding="5">
            <row>
                <cell>
                    <img src="" />
                </cell>
                <cell></cell>
                <cell span="8" padding="10">
                    [% IF invoice.title %]<row><cell><text class="title">[% invoice.title %]</text></cell></row>[% END %]
                    <row><cell><text class="busname">[% invoice.sender_name %]</text></cell></row>
                    [% IF invoice.sender_abn %]<row><cell><text>ABN: [% invoice.sender_abn %]</text></cell></row>[% END %]
                </cell>
            </row>
        </header>
        
        <row margin="5" padding="10" columns="16">
            <cell><text align="right">To:</text></cell>
            <cell span="10" padding="10">
                <row><cell><text font-face="HelveticaBold">[% invoice.recipient_name %][n]</text></cell></row>
                <row><cell>
            [%- FOR line IN invoice.recipient_address %]
[% line %][n]
[% END -%]
                </cell></row>
            </cell>
            <cell span="5">
                <text align="right">Date: [% invoice.date %]</text>
            </cell>
        </row>
        
        <section border="1" border-radius="10" margin="10" padding="10">
            <header>
                <row>
                    <cell span="4"><text class="heading">Description</text></cell>
                    <cell><text class="heading">Qty</text></cell>
                    <cell>
                        <text class="heading">
                            Unit Price[n]
                            (ex GST)
                        </text>
                    </cell>
                    <cell><text class="heading">GST Amount</text></cell>
                    <cell><text class="heading">
                        Amt Payable[n]
                        (inc GST)
                    </text></cell>
                </row>
            </header>

            [% FOR line IN items %]
                <row padding="5 0 0 0" margin="0 0 5 0" border="0 0 1 0" border-color="#CCCCCC">
                    <cell padding="0 0 0 5" span="4">[% line.desc %]</cell>
                    <cell><text align="right">[% line.qty %]</text></cell>
                    <cell ><text align="right">$[% line.price %]</text></cell>
                    <cell ><text align="right">$[% line.tax %]</text></cell>
                    <cell ><text align="right">$[% line.total %]</text></cell>
                </row>
            [% END %]

            <row columns="6">
                <cell span="3"><text class="total-amount">Totals</text></cell>
                <cell></cell>
                <cell></cell>
                <cell><text class="total-amount">[% invoice.currency.uc %]$[% invoice.total %]</text></cell>
            </row>
        
            <row columns="1"><cell>
                <row columns="8">
                    <cell span="7"><text class="total_label">TOTAL (ex [% invoice.tax_name %])</text></cell>
                    <cell><text class="total-amount">$[% invoice.sub_total %]</text></cell>
                </row>
                <row columns="8">
                    <cell span="7"><text class="total_label">TOTAL GST AMOUNT PAYABLE</text></cell>
                    <cell><text class="total-amount">$[% invoice.tax_amount %]</text></cell>
                </row>
                <row columns="8">
                    <cell span="7"><text class="total_label" font-face="Helvetica-Bold">TOTAL AMOUNT PAYABLE (inc GST)</text></cell>
                    <cell><text class="total-amount">[% invoice.currency.uc %]$[% invoice.total %]</text></cell>
                </row>
            </cell></row>
        </section>
        <footer>
            <row columns="1">pdfunicorn.com</row>
        </footer>
    </page>
</doc>
